// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/repository.go -destination=internal/repository/mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "avito-internship/internal/domain"
	repository "avito-internship/internal/repository"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// AddUsersToTeam mocks base method.
func (m *MockUserRepository) AddUsersToTeam(ctx context.Context, teamId int, users []domain.User) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUsersToTeam", ctx, teamId, users)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddUsersToTeam indicates an expected call of AddUsersToTeam.
func (mr *MockUserRepositoryMockRecorder) AddUsersToTeam(ctx, teamId, users any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUsersToTeam", reflect.TypeOf((*MockUserRepository)(nil).AddUsersToTeam), ctx, teamId, users)
}

// DeactivateUsers mocks base method.
func (m *MockUserRepository) DeactivateUsers(ctx context.Context, ids []string) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateUsers", ctx, ids)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeactivateUsers indicates an expected call of DeactivateUsers.
func (mr *MockUserRepositoryMockRecorder) DeactivateUsers(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateUsers", reflect.TypeOf((*MockUserRepository)(nil).DeactivateUsers), ctx, ids)
}

// GetById mocks base method.
func (m *MockUserRepository) GetById(ctx context.Context, userId string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, userId)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockUserRepositoryMockRecorder) GetById(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockUserRepository)(nil).GetById), ctx, userId)
}

// GetReassignCandidates mocks base method.
func (m *MockUserRepository) GetReassignCandidates(ctx context.Context, authorId string, excludeIds []string, maxCandidates int) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReassignCandidates", ctx, authorId, excludeIds, maxCandidates)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReassignCandidates indicates an expected call of GetReassignCandidates.
func (mr *MockUserRepositoryMockRecorder) GetReassignCandidates(ctx, authorId, excludeIds, maxCandidates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReassignCandidates", reflect.TypeOf((*MockUserRepository)(nil).GetReassignCandidates), ctx, authorId, excludeIds, maxCandidates)
}

// GetReviewCandidates mocks base method.
func (m *MockUserRepository) GetReviewCandidates(ctx context.Context, authorId string, maxCandidates int) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewCandidates", ctx, authorId, maxCandidates)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviewCandidates indicates an expected call of GetReviewCandidates.
func (mr *MockUserRepositoryMockRecorder) GetReviewCandidates(ctx, authorId, maxCandidates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewCandidates", reflect.TypeOf((*MockUserRepository)(nil).GetReviewCandidates), ctx, authorId, maxCandidates)
}

// UpdateIsActive mocks base method.
func (m *MockUserRepository) UpdateIsActive(ctx context.Context, userId string, isActive bool) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIsActive", ctx, userId, isActive)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateIsActive indicates an expected call of UpdateIsActive.
func (mr *MockUserRepositoryMockRecorder) UpdateIsActive(ctx, userId, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIsActive", reflect.TypeOf((*MockUserRepository)(nil).UpdateIsActive), ctx, userId, isActive)
}

// MockTeamRepository is a mock of TeamRepository interface.
type MockTeamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepositoryMockRecorder
	isgomock struct{}
}

// MockTeamRepositoryMockRecorder is the mock recorder for MockTeamRepository.
type MockTeamRepositoryMockRecorder struct {
	mock *MockTeamRepository
}

// NewMockTeamRepository creates a new mock instance.
func NewMockTeamRepository(ctrl *gomock.Controller) *MockTeamRepository {
	mock := &MockTeamRepository{ctrl: ctrl}
	mock.recorder = &MockTeamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepository) EXPECT() *MockTeamRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTeamRepository) Create(ctx context.Context, team domain.Team) (domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, team)
	ret0, _ := ret[0].(domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTeamRepositoryMockRecorder) Create(ctx, team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTeamRepository)(nil).Create), ctx, team)
}

// GetMembersByTeamNameWithUsers mocks base method.
func (m *MockTeamRepository) GetMembersByTeamNameWithUsers(ctx context.Context, teamName string) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembersByTeamNameWithUsers", ctx, teamName)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembersByTeamNameWithUsers indicates an expected call of GetMembersByTeamNameWithUsers.
func (mr *MockTeamRepositoryMockRecorder) GetMembersByTeamNameWithUsers(ctx, teamName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembersByTeamNameWithUsers", reflect.TypeOf((*MockTeamRepository)(nil).GetMembersByTeamNameWithUsers), ctx, teamName)
}

// GetTeamByUserId mocks base method.
func (m *MockTeamRepository) GetTeamByUserId(ctx context.Context, userId string) (domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamByUserId", ctx, userId)
	ret0, _ := ret[0].(domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamByUserId indicates an expected call of GetTeamByUserId.
func (mr *MockTeamRepositoryMockRecorder) GetTeamByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamByUserId", reflect.TypeOf((*MockTeamRepository)(nil).GetTeamByUserId), ctx, userId)
}

// MockPullRequestRepository is a mock of PullRequestRepository interface.
type MockPullRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPullRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockPullRequestRepositoryMockRecorder is the mock recorder for MockPullRequestRepository.
type MockPullRequestRepositoryMockRecorder struct {
	mock *MockPullRequestRepository
}

// NewMockPullRequestRepository creates a new mock instance.
func NewMockPullRequestRepository(ctrl *gomock.Controller) *MockPullRequestRepository {
	mock := &MockPullRequestRepository{ctrl: ctrl}
	mock.recorder = &MockPullRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullRequestRepository) EXPECT() *MockPullRequestRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPullRequestRepository) Create(ctx context.Context, pullRequest domain.PullRequest) (domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pullRequest)
	ret0, _ := ret[0].(domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPullRequestRepositoryMockRecorder) Create(ctx, pullRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPullRequestRepository)(nil).Create), ctx, pullRequest)
}

// GetByPrIdWithReviewersIds mocks base method.
func (m *MockPullRequestRepository) GetByPrIdWithReviewersIds(ctx context.Context, prId string) (repository.GetByPrIdWithReviewersIdsDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPrIdWithReviewersIds", ctx, prId)
	ret0, _ := ret[0].(repository.GetByPrIdWithReviewersIdsDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPrIdWithReviewersIds indicates an expected call of GetByPrIdWithReviewersIds.
func (mr *MockPullRequestRepositoryMockRecorder) GetByPrIdWithReviewersIds(ctx, prId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPrIdWithReviewersIds", reflect.TypeOf((*MockPullRequestRepository)(nil).GetByPrIdWithReviewersIds), ctx, prId)
}

// GetOpenPRsByReviewerIDs mocks base method.
func (m *MockPullRequestRepository) GetOpenPRsByReviewerIDs(ctx context.Context, prIds []string, statusId int) (map[string]repository.GetOpenPRsByReviewerIDsDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenPRsByReviewerIDs", ctx, prIds, statusId)
	ret0, _ := ret[0].(map[string]repository.GetOpenPRsByReviewerIDsDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpenPRsByReviewerIDs indicates an expected call of GetOpenPRsByReviewerIDs.
func (mr *MockPullRequestRepositoryMockRecorder) GetOpenPRsByReviewerIDs(ctx, prIds, statusId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenPRsByReviewerIDs", reflect.TypeOf((*MockPullRequestRepository)(nil).GetOpenPRsByReviewerIDs), ctx, prIds, statusId)
}

// SetMergedStatus mocks base method.
func (m *MockPullRequestRepository) SetMergedStatus(ctx context.Context, statusId int, prId string) (repository.SetMergedStatusDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMergedStatus", ctx, statusId, prId)
	ret0, _ := ret[0].(repository.SetMergedStatusDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetMergedStatus indicates an expected call of SetMergedStatus.
func (mr *MockPullRequestRepositoryMockRecorder) SetMergedStatus(ctx, statusId, prId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMergedStatus", reflect.TypeOf((*MockPullRequestRepository)(nil).SetMergedStatus), ctx, statusId, prId)
}

// MockPrReviewerRepository is a mock of PrReviewerRepository interface.
type MockPrReviewerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPrReviewerRepositoryMockRecorder
	isgomock struct{}
}

// MockPrReviewerRepositoryMockRecorder is the mock recorder for MockPrReviewerRepository.
type MockPrReviewerRepositoryMockRecorder struct {
	mock *MockPrReviewerRepository
}

// NewMockPrReviewerRepository creates a new mock instance.
func NewMockPrReviewerRepository(ctrl *gomock.Controller) *MockPrReviewerRepository {
	mock := &MockPrReviewerRepository{ctrl: ctrl}
	mock.recorder = &MockPrReviewerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrReviewerRepository) EXPECT() *MockPrReviewerRepositoryMockRecorder {
	return m.recorder
}

// AddReviewers mocks base method.
func (m *MockPrReviewerRepository) AddReviewers(ctx context.Context, pullRequestId string, reviewersId []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReviewers", ctx, pullRequestId, reviewersId)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddReviewers indicates an expected call of AddReviewers.
func (mr *MockPrReviewerRepositoryMockRecorder) AddReviewers(ctx, pullRequestId, reviewersId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReviewers", reflect.TypeOf((*MockPrReviewerRepository)(nil).AddReviewers), ctx, pullRequestId, reviewersId)
}

// GetPRByReviewer mocks base method.
func (m *MockPrReviewerRepository) GetPRByReviewer(ctx context.Context, userId string) (repository.GetPRByReviewerDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRByReviewer", ctx, userId)
	ret0, _ := ret[0].(repository.GetPRByReviewerDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRByReviewer indicates an expected call of GetPRByReviewer.
func (mr *MockPrReviewerRepositoryMockRecorder) GetPRByReviewer(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRByReviewer", reflect.TypeOf((*MockPrReviewerRepository)(nil).GetPRByReviewer), ctx, userId)
}

// UpdateReviewer mocks base method.
func (m *MockPrReviewerRepository) UpdateReviewer(ctx context.Context, oldUserId, newUserId, pullRequestId string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReviewer", ctx, oldUserId, newUserId, pullRequestId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateReviewer indicates an expected call of UpdateReviewer.
func (mr *MockPrReviewerRepositoryMockRecorder) UpdateReviewer(ctx, oldUserId, newUserId, pullRequestId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReviewer", reflect.TypeOf((*MockPrReviewerRepository)(nil).UpdateReviewer), ctx, oldUserId, newUserId, pullRequestId)
}

// UpdateReviewers mocks base method.
func (m *MockPrReviewerRepository) UpdateReviewers(ctx context.Context, changes map[string]repository.PrReviewerChange) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReviewers", ctx, changes)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReviewers indicates an expected call of UpdateReviewers.
func (mr *MockPrReviewerRepositoryMockRecorder) UpdateReviewers(ctx, changes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReviewers", reflect.TypeOf((*MockPrReviewerRepository)(nil).UpdateReviewers), ctx, changes)
}

// MockStatusRepository is a mock of StatusRepository interface.
type MockStatusRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStatusRepositoryMockRecorder
	isgomock struct{}
}

// MockStatusRepositoryMockRecorder is the mock recorder for MockStatusRepository.
type MockStatusRepositoryMockRecorder struct {
	mock *MockStatusRepository
}

// NewMockStatusRepository creates a new mock instance.
func NewMockStatusRepository(ctrl *gomock.Controller) *MockStatusRepository {
	mock := &MockStatusRepository{ctrl: ctrl}
	mock.recorder = &MockStatusRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusRepository) EXPECT() *MockStatusRepositoryMockRecorder {
	return m.recorder
}

// GetById mocks base method.
func (m *MockStatusRepository) GetById(ctx context.Context, statusId int) (domain.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, statusId)
	ret0, _ := ret[0].(domain.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockStatusRepositoryMockRecorder) GetById(ctx, statusId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockStatusRepository)(nil).GetById), ctx, statusId)
}

// GetByName mocks base method.
func (m *MockStatusRepository) GetByName(ctx context.Context, statusName string) (domain.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, statusName)
	ret0, _ := ret[0].(domain.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockStatusRepositoryMockRecorder) GetByName(ctx, statusName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockStatusRepository)(nil).GetByName), ctx, statusName)
}
